import type {
  Finding,
  SecurityReport,
  Severity,
  Grade,
  RuntimeConfidence,
  SkillHealth,
} from "../types.js";

/**
 * Render a security report as a self-contained HTML file.
 * All CSS is inline in a <style> tag — no external dependencies.
 * Dark theme inspired by GitHub dark mode.
 */
export function renderHtmlReport(report: SecurityReport): string {
  const gradeMeta = gradeMetadata(report.score.grade);
  const findings = [...report.findings];
  const s = report.summary;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AgentShield Security Report — Grade ${report.score.grade}</title>
  <style>${inlineStyles()}</style>
</head>
<body>
  <div class="container">

    <!-- Header -->
    <header class="header">
      <div class="header-content">
        <div class="grade-badge" style="background-color: ${gradeMeta.color};">
          <span class="grade-letter">${report.score.grade}</span>
        </div>
        <div class="header-info">
          <h1 class="title">AgentShield Security Report</h1>
          <p class="subtitle">Score: <strong>${report.score.numericScore}</strong>/100</p>
          <p class="meta">Target: ${escapeHtml(report.targetPath)}</p>
          <p class="meta">Scanned: ${formatTimestamp(report.timestamp)}</p>
        </div>
      </div>
    </header>

    ${renderExecutiveSummary(report)}

    <!-- Summary Stats -->
    <section class="section">
      <h2 class="section-title">Summary</h2>
      <div class="stats-grid">
        ${renderStatCard("Files Scanned", String(s.filesScanned), "files")}
        ${renderStatCard("Total Findings", String(s.totalFindings), "findings")}
        ${renderStatCard("Auto-Fixable", String(s.autoFixable), "fixable")}
        ${renderStatCard("Critical", String(s.critical), "critical")}
        ${renderStatCard("High", String(s.high), "high")}
        ${renderStatCard("Medium", String(s.medium), "medium")}
        ${renderStatCard("Low", String(s.low), "low")}
        ${renderStatCard("Info", String(s.info), "info")}
      </div>
    </section>

    <!-- Score Breakdown -->
    <section class="section">
      <h2 class="section-title">Score Breakdown</h2>
      <div class="breakdown">
        ${renderScoreBar("Secrets", report.score.breakdown.secrets)}
        ${renderScoreBar("Permissions", report.score.breakdown.permissions)}
        ${renderScoreBar("Hooks", report.score.breakdown.hooks)}
        ${renderScoreBar("MCP Servers", report.score.breakdown.mcp)}
        ${renderScoreBar("Agents", report.score.breakdown.agents)}
      </div>
    </section>

    ${report.harnessAdapters
      ? `<section class="section">
      <h2 class="section-title">Harness Adapters</h2>
      <p class="executive-copy">Matched ${report.harnessAdapters.totalMatched}/${report.harnessAdapters.totalRegistered} registered adapters.</p>
      <div>
        ${report.harnessAdapters.matched.length === 0
          ? '<p class="executive-copy muted">No harness-specific markers were detected.</p>'
          : report.harnessAdapters.matched.map((adapter) => renderHarnessAdapterCard(adapter)).join("")}
      </div>
    </section>`
      : ""}

    ${report.skillHealth && report.skillHealth.totalSkills > 0
      ? `<section class="section">
      <h2 class="section-title">Skill Health</h2>
      <div class="stats-grid">
        ${renderStatCard("Skills", String(report.skillHealth.totalSkills), "files")}
        ${renderStatCard("Instrumented", String(report.skillHealth.instrumentedSkills), "fixable")}
        ${renderStatCard("Versioned", String(report.skillHealth.versionedSkills), "medium")}
        ${renderStatCard("Rollback-ready", String(report.skillHealth.rollbackReadySkills), "high")}
        ${renderStatCard("With history", String(report.skillHealth.observedSkills), "info")}
        ${typeof report.skillHealth.averageScore === "number"
          ? renderStatCard("Avg health", `${report.skillHealth.averageScore}/100`, "findings")
          : ""}
      </div>
      <div>
        ${report.skillHealth.skills.map((skill) => renderSkillHealthCard(skill)).join("")}
      </div>
    </section>`
      : ""}

    <!-- Severity Distribution -->
    <section class="section">
      <h2 class="section-title">Severity Distribution</h2>
      <div class="distribution">
        ${renderDistributionChart(s)}
      </div>
    </section>

    <!-- Findings -->
    <section class="section">
      <h2 class="section-title">Findings</h2>
      ${findings.length === 0
        ? '<div class="no-findings"><p>No security issues found. Your configuration looks good!</p></div>'
        : renderFindingsGrouped(findings)}
    </section>

    <!-- Footer -->
    <footer class="footer">
      <p>Generated by <strong>AgentShield</strong> &mdash; Security auditor for AI agent configurations</p>
      <p class="footer-timestamp">${formatTimestamp(report.timestamp)}</p>
    </footer>

  </div>
</body>
</html>`;
}

// ─── Executive Summary ───────────────────────────────────────

interface ExecutivePosture {
  readonly label: string;
  readonly detail: string;
  readonly color: string;
}

function renderExecutiveSummary(report: SecurityReport): string {
  const posture = executivePosture(report);
  const priorities = executivePriorityFindings(report.findings);
  const priorityItems =
    priorities.length === 0
      ? '<li class="priority-item muted">No executive action items.</li>'
      : priorities
        .map((finding) => {
          const location = finding.line ? `${finding.file}:${finding.line}` : finding.file;
          return `<li class="priority-item">
            <span class="priority-severity" style="background-color: ${severityColor(finding.severity)};">${finding.severity.toUpperCase()}</span>
            <span>
              <strong>${escapeHtml(finding.title)}</strong>
              <span class="priority-meta">${escapeHtml(location)} - ${escapeHtml(finding.category)}</span>
            </span>
          </li>`;
        })
        .join("");

  return `
    <!-- Executive Summary -->
    <section class="section executive-summary">
      <h2 class="section-title">Executive Summary</h2>
      <div class="executive-grid">
        <div class="executive-card posture-card" style="border-color: ${posture.color};">
          <span class="executive-label">Risk Posture</span>
          <strong class="posture-title" style="color: ${posture.color};">${escapeHtml(posture.label)}</strong>
          <p class="executive-copy">${escapeHtml(posture.detail)}</p>
        </div>
        <div class="executive-card">
          <span class="executive-label">Executive Priorities</span>
          <ul class="priority-list">${priorityItems}</ul>
        </div>
        <div class="executive-card">
          <span class="executive-label">Category Exposure</span>
          ${renderCategoryExposure(report.findings)}
        </div>
      </div>
    </section>`;
}

function executivePosture(report: SecurityReport): ExecutivePosture {
  const { summary } = report;

  if (summary.critical > 0) {
    return {
      label: "Immediate remediation required",
      detail: formatOwnerReviewDetail(summary.critical, summary.high),
      color: "#f85149",
    };
  }

  if (summary.high > 0) {
    return {
      label: "High-risk changes need review",
      detail: `${summary.high} high-severity findings require owner review before rollout.`,
      color: "#d29922",
    };
  }

  if (summary.medium > 0) {
    return {
      label: "Monitor before broad rollout",
      detail: `${summary.medium} medium-severity findings should be reviewed before broad rollout.`,
      color: "#388bfd",
    };
  }

  return {
    label: "Ready for standard rollout",
    detail: "No critical or high-severity findings were detected.",
    color: "#2ea043",
  };
}

function formatOwnerReviewDetail(critical: number, high: number): string {
  if (critical > 0 && high > 0) {
    return `${critical} critical and ${high} high-severity findings require owner review.`;
  }

  if (critical > 0) {
    return `${critical} critical findings require owner review.`;
  }

  return `${high} high-severity findings require owner review before rollout.`;
}

function executivePriorityFindings(findings: ReadonlyArray<Finding>): ReadonlyArray<Finding> {
  const severityRank: Record<Severity, number> = {
    critical: 0,
    high: 1,
    medium: 2,
    low: 3,
    info: 4,
  };

  return findings
    .filter((finding) => finding.severity === "critical" || finding.severity === "high")
    .slice()
    .sort((a, b) => severityRank[a.severity] - severityRank[b.severity])
    .slice(0, 5);
}

function renderCategoryExposure(findings: ReadonlyArray<Finding>): string {
  if (findings.length === 0) {
    return '<p class="executive-copy muted">No category exposure to display.</p>';
  }

  const categoryCounts = new Map<string, number>();
  for (const finding of findings) {
    categoryCounts.set(finding.category, (categoryCounts.get(finding.category) ?? 0) + 1);
  }

  const rows = [...categoryCounts.entries()]
    .sort(([leftCategory, leftCount], [rightCategory, rightCount]) => {
      if (rightCount !== leftCount) return rightCount - leftCount;
      return leftCategory.localeCompare(rightCategory);
    })
    .map(([category, count]) => {
      const noun = count === 1 ? "finding" : "findings";
      return `<div class="exposure-row">
        <span class="exposure-category">${escapeHtml(category)}</span>
        <span class="exposure-count">${count} ${noun}</span>
      </div>`;
    })
    .join("");

  return `<div class="exposure-grid">${rows}</div>`;
}

// ─── Grade Metadata ──────────────────────────────────────────

interface GradeMeta {
  readonly color: string;
  readonly label: string;
}

function gradeMetadata(grade: Grade): GradeMeta {
  const map: Record<Grade, GradeMeta> = {
    A: { color: "#2ea043", label: "Excellent" },
    B: { color: "#388bfd", label: "Good" },
    C: { color: "#d29922", label: "Fair" },
    D: { color: "#db6d28", label: "Poor" },
    F: { color: "#f85149", label: "Critical" },
  };
  return map[grade];
}

// ─── Severity Colors ─────────────────────────────────────────

function severityColor(severity: Severity): string {
  const colors: Record<Severity, string> = {
    critical: "#f85149",
    high: "#d29922",
    medium: "#388bfd",
    low: "#8b949e",
    info: "#6e7681",
  };
  return colors[severity];
}

// ─── Score Bar ───────────────────────────────────────────────

function scoreBarColor(score: number): string {
  if (score >= 80) return "#2ea043";
  if (score >= 60) return "#d29922";
  return "#f85149";
}

function renderScoreBar(label: string, score: number): string {
  const color = scoreBarColor(score);
  const pct = Math.max(0, Math.min(100, score));

  return `
    <div class="bar-row">
      <span class="bar-label">${escapeHtml(label)}</span>
      <div class="bar-track">
        <div class="bar-fill" style="width: ${pct}%; background-color: ${color};"></div>
      </div>
      <span class="bar-value" style="color: ${color};">${score}/100</span>
    </div>`;
}

// ─── Stat Card ───────────────────────────────────────────────

function renderStatCard(label: string, value: string, kind: string): string {
  const kindColorMap: Record<string, string> = {
    files: "#8b949e",
    findings: "#e6edf3",
    fixable: "#2ea043",
    critical: "#f85149",
    high: "#d29922",
    medium: "#388bfd",
    low: "#8b949e",
    info: "#6e7681",
  };
  const color = kindColorMap[kind] ?? "#e6edf3";

  return `
    <div class="stat-card">
      <div class="stat-value" style="color: ${color};">${escapeHtml(value)}</div>
      <div class="stat-label">${escapeHtml(label)}</div>
    </div>`;
}

// ─── Distribution Chart (SVG) ────────────────────────────────

function renderDistributionChart(summary: {
  readonly critical: number;
  readonly high: number;
  readonly medium: number;
  readonly low: number;
  readonly info: number;
}): string {
  const segments: ReadonlyArray<{
    readonly label: string;
    readonly count: number;
    readonly color: string;
  }> = [
    { label: "Critical", count: summary.critical, color: "#f85149" },
    { label: "High", count: summary.high, color: "#d29922" },
    { label: "Medium", count: summary.medium, color: "#388bfd" },
    { label: "Low", count: summary.low, color: "#8b949e" },
    { label: "Info", count: summary.info, color: "#6e7681" },
  ];

  const total = segments.reduce((acc, seg) => acc + seg.count, 0);

  if (total === 0) {
    return '<p class="no-findings-text">No findings to display.</p>';
  }

  const barWidth = 600;
  const barHeight = 32;
  let xOffset = 0;

  const rects = segments.map((seg) => {
    const width = total > 0 ? (seg.count / total) * barWidth : 0;
    const rect =
      width > 0
        ? `<rect x="${xOffset}" y="0" width="${width}" height="${barHeight}" fill="${seg.color}" rx="0" />`
        : "";
    xOffset += width;
    return rect;
  });

  const legend = segments
    .filter((seg) => seg.count > 0)
    .map(
      (seg) =>
        `<span class="legend-item"><span class="legend-dot" style="background-color: ${seg.color};"></span>${escapeHtml(seg.label)}: ${seg.count}</span>`
    )
    .join("");

  return `
    <svg class="dist-bar" viewBox="0 0 ${barWidth} ${barHeight}" preserveAspectRatio="none">
      <rect x="0" y="0" width="${barWidth}" height="${barHeight}" fill="#21262d" rx="6" />
      <clipPath id="bar-clip"><rect x="0" y="0" width="${barWidth}" height="${barHeight}" rx="6" /></clipPath>
      <g clip-path="url(#bar-clip)">${rects.join("")}</g>
    </svg>
    <div class="legend">${legend}</div>`;
}

// ─── Findings (grouped by severity) ─────────────────────────

function renderFindingsGrouped(findings: ReadonlyArray<Finding>): string {
  const severities: ReadonlyArray<Severity> = ["critical", "high", "medium", "low", "info"];
  const grouped = severities.map(
    (sev) =>
      [sev, findings.filter((f) => f.severity === sev)] as const
  );

  return grouped
    .filter(([, items]) => items.length > 0)
    .map(([sev, items]) => {
      const color = severityColor(sev);
      const cards = items.map((f) => renderFindingCard(f)).join("");

      return `
        <div class="findings-group">
          <h3 class="group-header" style="color: ${color};">
            <span class="severity-dot" style="background-color: ${color};"></span>
            ${sev.toUpperCase()} (${items.length})
          </h3>
          ${cards}
        </div>`;
    })
    .join("");
}

function renderFindingCard(finding: Finding): string {
  const color = severityColor(finding.severity);
  const location = finding.line
    ? `${escapeHtml(finding.file)}:${finding.line}`
    : escapeHtml(finding.file);
  const runtimeConfidenceBadge = finding.runtimeConfidence
    ? `<span class="runtime-confidence-badge">${escapeHtml(formatRuntimeConfidence(finding.runtimeConfidence))}</span>`
    : "";

  const evidenceBlock = finding.evidence
    ? `<div class="finding-evidence"><strong>Evidence:</strong><pre><code>${escapeHtml(finding.evidence)}</code></pre></div>`
    : "";

  const fixBlock = finding.fix
    ? `<div class="finding-fix">
        <strong>Fix:</strong> ${escapeHtml(finding.fix.description)}
        ${finding.fix.auto ? '<span class="auto-fix-badge">auto-fixable</span>' : ""}
        ${finding.fix.before ? `<div class="fix-diff"><div class="diff-before"><strong>Before:</strong><pre><code>${escapeHtml(finding.fix.before)}</code></pre></div><div class="diff-after"><strong>After:</strong><pre><code>${escapeHtml(finding.fix.after)}</code></pre></div></div>` : ""}
      </div>`
    : "";

  return `
    <div class="finding-card">
      <div class="finding-header">
        <span class="severity-badge" style="background-color: ${color};">${finding.severity.toUpperCase()}</span>
        ${runtimeConfidenceBadge}
        <span class="finding-title">${escapeHtml(finding.title)}</span>
      </div>
      <div class="finding-meta">
        <span class="finding-category">${escapeHtml(finding.category)}</span>
        <span class="finding-location">${location}</span>
      </div>
      <p class="finding-description">${escapeHtml(finding.description)}</p>
      ${evidenceBlock}
      ${fixBlock}
    </div>`;
}

function renderSkillHealthCard(skill: SkillHealth): string {
  const score = typeof skill.score === "number" ? `${skill.score}/100` : "unobserved";
  const detail = typeof skill.successRate === "number"
    ? `Runs ${skill.observedRuns} • Success ${Math.round(skill.successRate * 100)}%${
        typeof skill.averageFeedback === "number"
          ? ` • Feedback ${skill.averageFeedback.toFixed(1)}/5`
          : ""
      }`
    : "No execution history found";

  return `
    <div class="finding-card">
      <div class="finding-header">
        <span class="runtime-confidence-badge">${escapeHtml(skill.status)}</span>
        <span class="finding-title">${escapeHtml(skill.skillName)}</span>
      </div>
      <div class="finding-meta">
        <span class="finding-category">skill health</span>
        <span class="finding-location">${escapeHtml(skill.file)}</span>
      </div>
      <p class="finding-description">${escapeHtml(`${score} — ${detail}`)}</p>
    </div>`;
}

function renderHarnessAdapterCard(
  adapter: NonNullable<SecurityReport["harnessAdapters"]>["matched"][number]
): string {
  const evidence = adapter.evidence.length > 0
    ? adapter.evidence.map((item) => `<code>${escapeHtml(item)}</code>`).join(", ")
    : "No markers";

  return `
    <div class="finding-card">
      <div class="finding-header">
        <span class="runtime-confidence-badge">${escapeHtml(adapter.confidence)}</span>
        <span class="finding-title">${escapeHtml(adapter.name)}</span>
      </div>
      <div class="finding-meta">
        <span class="finding-category">harness adapter</span>
        <span class="finding-location">${evidence}</span>
      </div>
      <p class="finding-description">${escapeHtml(adapter.description)}</p>
      <p class="finding-description"><strong>Permission concepts:</strong> ${escapeHtml(adapter.permissionConcepts.join(", "))}</p>
      <p class="finding-description"><strong>Plugin surfaces:</strong> ${escapeHtml(adapter.pluginSurfaces.join(", "))}</p>
    </div>`;
}

function formatRuntimeConfidence(value: RuntimeConfidence): string {
  switch (value) {
    case "active-runtime":
      return "active runtime";
    case "project-local-optional":
      return "project-local optional";
    case "template-example":
      return "template/example";
    case "docs-example":
      return "docs/example";
    case "plugin-cache":
      return "plugin cache";
    case "plugin-manifest":
      return "plugin manifest";
    case "hook-code":
      return "hook-code implementation";
  }
}

// ─── Timestamp Formatting ────────────────────────────────────

function formatTimestamp(iso: string): string {
  try {
    const date = new Date(iso);
    return date.toLocaleString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      timeZoneName: "short",
    });
  } catch {
    return iso;
  }
}

// ─── Escape HTML ─────────────────────────────────────────────

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

// ─── Inline Styles ───────────────────────────────────────────

function inlineStyles(): string {
  return `
    /* Reset & Base */
    *, *::before, *::after {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;
      background-color: #0d1117;
      color: #e6edf3;
      line-height: 1.6;
      -webkit-font-smoothing: antialiased;
    }

    .container {
      max-width: 960px;
      margin: 0 auto;
      padding: 24px 16px;
    }

    /* Header */
    .header {
      background: linear-gradient(135deg, #161b22 0%, #0d1117 100%);
      border: 1px solid #30363d;
      border-radius: 12px;
      padding: 32px;
      margin-bottom: 24px;
    }

    .header-content {
      display: flex;
      align-items: center;
      gap: 32px;
      flex-wrap: wrap;
    }

    .grade-badge {
      width: 120px;
      height: 120px;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
      box-shadow: 0 0 40px rgba(0, 0, 0, 0.4);
    }

    .grade-letter {
      font-size: 64px;
      font-weight: 800;
      color: #ffffff;
      text-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
    }

    .header-info {
      flex: 1;
      min-width: 200px;
    }

    .title {
      font-size: 28px;
      font-weight: 700;
      color: #e6edf3;
      margin-bottom: 4px;
    }

    .subtitle {
      font-size: 20px;
      color: #8b949e;
      margin-bottom: 8px;
    }

    .subtitle strong {
      color: #e6edf3;
      font-size: 24px;
    }

    .meta {
      font-size: 14px;
      color: #6e7681;
      margin-bottom: 2px;
    }

    /* Section */
    .section {
      background: #161b22;
      border: 1px solid #30363d;
      border-radius: 12px;
      padding: 24px;
      margin-bottom: 24px;
    }

    .section-title {
      font-size: 20px;
      font-weight: 600;
      color: #e6edf3;
      margin-bottom: 16px;
      padding-bottom: 8px;
      border-bottom: 1px solid #21262d;
    }

    /* Executive Summary */
    .executive-summary {
      border-color: #3d444d;
    }

    .executive-grid {
      display: grid;
      grid-template-columns: minmax(0, 1.1fr) minmax(0, 1fr);
      gap: 12px;
    }

    .executive-card {
      background: #0d1117;
      border: 1px solid #21262d;
      border-radius: 8px;
      padding: 16px;
    }

    .posture-card {
      grid-row: span 2;
    }

    .executive-label {
      display: block;
      font-size: 12px;
      color: #8b949e;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 8px;
    }

    .posture-title {
      display: block;
      font-size: 18px;
      margin-bottom: 8px;
    }

    .executive-copy {
      font-size: 14px;
      color: #8b949e;
    }

    .muted {
      color: #8b949e;
    }

    .priority-list {
      list-style: none;
      display: flex;
      flex-direction: column;
      gap: 10px;
    }

    .priority-item {
      display: flex;
      align-items: flex-start;
      gap: 8px;
      font-size: 14px;
      color: #e6edf3;
    }

    .priority-severity {
      color: #ffffff;
      font-size: 10px;
      font-weight: 700;
      letter-spacing: 0.5px;
      border-radius: 10px;
      padding: 2px 7px;
      flex-shrink: 0;
      margin-top: 2px;
    }

    .priority-meta {
      display: block;
      color: #8b949e;
      font-size: 12px;
      margin-top: 2px;
      overflow-wrap: anywhere;
    }

    .exposure-grid {
      display: flex;
      flex-direction: column;
      gap: 8px;
    }

    .exposure-row {
      display: flex;
      justify-content: space-between;
      gap: 12px;
      border-bottom: 1px solid #21262d;
      padding-bottom: 8px;
      font-size: 14px;
    }

    .exposure-row:last-child {
      border-bottom: 0;
      padding-bottom: 0;
    }

    .exposure-category {
      color: #e6edf3;
      font-weight: 600;
    }

    .exposure-count {
      color: #8b949e;
      white-space: nowrap;
    }

    /* Stats Grid */
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
      gap: 12px;
    }

    .stat-card {
      background: #0d1117;
      border: 1px solid #21262d;
      border-radius: 8px;
      padding: 16px;
      text-align: center;
    }

    .stat-value {
      font-size: 28px;
      font-weight: 700;
      line-height: 1.2;
    }

    .stat-label {
      font-size: 12px;
      color: #8b949e;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-top: 4px;
    }

    /* Score Breakdown Bars */
    .breakdown {
      display: flex;
      flex-direction: column;
      gap: 12px;
    }

    .bar-row {
      display: flex;
      align-items: center;
      gap: 12px;
    }

    .bar-label {
      width: 120px;
      font-size: 14px;
      color: #8b949e;
      text-align: right;
      flex-shrink: 0;
    }

    .bar-track {
      flex: 1;
      height: 20px;
      background: #21262d;
      border-radius: 10px;
      overflow: hidden;
    }

    .bar-fill {
      height: 100%;
      border-radius: 10px;
      transition: width 0.3s ease;
    }

    .bar-value {
      width: 70px;
      font-size: 14px;
      font-weight: 600;
      text-align: right;
      flex-shrink: 0;
    }

    /* Distribution */
    .distribution {
      display: flex;
      flex-direction: column;
      gap: 12px;
    }

    .dist-bar {
      width: 100%;
      height: 32px;
      border-radius: 6px;
    }

    .legend {
      display: flex;
      flex-wrap: wrap;
      gap: 16px;
    }

    .legend-item {
      display: flex;
      align-items: center;
      gap: 6px;
      font-size: 13px;
      color: #8b949e;
    }

    .legend-dot {
      width: 10px;
      height: 10px;
      border-radius: 50%;
      display: inline-block;
      flex-shrink: 0;
    }

    .no-findings-text {
      color: #8b949e;
      font-style: italic;
    }

    /* Findings */
    .findings-group {
      margin-bottom: 20px;
    }

    .group-header {
      font-size: 16px;
      font-weight: 600;
      margin-bottom: 12px;
      display: flex;
      align-items: center;
      gap: 8px;
    }

    .severity-dot {
      width: 10px;
      height: 10px;
      border-radius: 50%;
      display: inline-block;
      flex-shrink: 0;
    }

    .finding-card {
      background: #0d1117;
      border: 1px solid #21262d;
      border-radius: 8px;
      padding: 16px;
      margin-bottom: 12px;
    }

    .finding-header {
      display: flex;
      align-items: center;
      gap: 10px;
      margin-bottom: 8px;
      flex-wrap: wrap;
    }

    .severity-badge {
      font-size: 11px;
      font-weight: 700;
      color: #ffffff;
      padding: 2px 8px;
      border-radius: 12px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      flex-shrink: 0;
    }

    .runtime-confidence-badge {
      font-size: 11px;
      font-weight: 600;
      color: #c9d1d9;
      background: #161b22;
      border: 1px solid #30363d;
      padding: 2px 8px;
      border-radius: 12px;
      text-transform: uppercase;
      letter-spacing: 0.3px;
      flex-shrink: 0;
    }

    .finding-title {
      font-size: 16px;
      font-weight: 600;
      color: #e6edf3;
    }

    .finding-meta {
      display: flex;
      gap: 16px;
      margin-bottom: 8px;
      flex-wrap: wrap;
    }

    .finding-category {
      font-size: 12px;
      color: #8b949e;
      background: #21262d;
      padding: 2px 8px;
      border-radius: 4px;
    }

    .finding-location {
      font-size: 12px;
      color: #6e7681;
      font-family: 'SF Mono', SFMono-Regular, Consolas, 'Liberation Mono', Menlo, monospace;
    }

    .finding-description {
      font-size: 14px;
      color: #8b949e;
      margin-bottom: 8px;
    }

    .finding-evidence {
      margin-top: 8px;
    }

    .finding-evidence strong,
    .finding-fix strong {
      font-size: 12px;
      color: #8b949e;
      text-transform: uppercase;
      letter-spacing: 0.3px;
    }

    .finding-evidence pre,
    .fix-diff pre {
      background: #161b22;
      border: 1px solid #21262d;
      border-radius: 6px;
      padding: 12px;
      margin-top: 4px;
      overflow-x: auto;
    }

    .finding-evidence code,
    .fix-diff code {
      font-family: 'SF Mono', SFMono-Regular, Consolas, 'Liberation Mono', Menlo, monospace;
      font-size: 13px;
      color: #e6edf3;
      white-space: pre-wrap;
      word-break: break-all;
    }

    .finding-fix {
      margin-top: 12px;
      font-size: 14px;
      color: #8b949e;
    }

    .auto-fix-badge {
      display: inline-block;
      font-size: 11px;
      font-weight: 600;
      color: #2ea043;
      background: rgba(46, 160, 67, 0.15);
      border: 1px solid rgba(46, 160, 67, 0.4);
      padding: 1px 6px;
      border-radius: 4px;
      margin-left: 8px;
    }

    .fix-diff {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 8px;
      margin-top: 8px;
    }

    .diff-before strong {
      color: #f85149;
    }

    .diff-after strong {
      color: #2ea043;
    }

    .no-findings {
      background: rgba(46, 160, 67, 0.1);
      border: 1px solid rgba(46, 160, 67, 0.3);
      border-radius: 8px;
      padding: 24px;
      text-align: center;
      color: #2ea043;
      font-size: 16px;
    }

    /* Footer */
    .footer {
      text-align: center;
      padding: 24px;
      color: #6e7681;
      font-size: 13px;
      border-top: 1px solid #21262d;
      margin-top: 12px;
    }

    .footer strong {
      color: #8b949e;
    }

    .footer-timestamp {
      margin-top: 4px;
      font-size: 12px;
    }

    /* Responsive */
    @media (max-width: 640px) {
      .header-content {
        flex-direction: column;
        text-align: center;
      }

      .bar-label {
        width: 80px;
        font-size: 12px;
      }

      .bar-value {
        width: 60px;
        font-size: 12px;
      }

      .fix-diff {
        grid-template-columns: 1fr;
      }

      .executive-grid {
        grid-template-columns: 1fr;
      }

      .posture-card {
        grid-row: auto;
      }

      .stats-grid {
        grid-template-columns: repeat(2, 1fr);
      }
    }
  `;
}
